// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: usertodo.proto

package usecase

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *Getrequest, opts ...client.CallOption) (*GetResponse, error)
	GetUserTodos(ctx context.Context, in *Getrequest, opts ...client.CallOption) (*GetAllTodoResponse, error)
	GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*GetAllResponse, error)
	Updateuser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	Deleteuser(ctx context.Context, in *User, opts ...client.CallOption) (*DeleteResponse, error)
	Auth(ctx context.Context, in *User, opts ...client.CallOption) (*Token, error)
	ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "usecase"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "UserService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Get(ctx context.Context, in *Getrequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.Get", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserTodos(ctx context.Context, in *Getrequest, opts ...client.CallOption) (*GetAllTodoResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserTodos", in)
	out := new(GetAllTodoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*GetAllResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetAll", in)
	out := new(GetAllResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Updateuser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "UserService.Updateuser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Deleteuser(ctx context.Context, in *User, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.Deleteuser", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Auth(ctx context.Context, in *User, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "UserService.Auth", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "UserService.ValidateToken", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Create(context.Context, *User, *Response) error
	Get(context.Context, *Getrequest, *GetResponse) error
	GetUserTodos(context.Context, *Getrequest, *GetAllTodoResponse) error
	GetAll(context.Context, *Request, *GetAllResponse) error
	Updateuser(context.Context, *User, *Response) error
	Deleteuser(context.Context, *User, *DeleteResponse) error
	Auth(context.Context, *User, *Token) error
	ValidateToken(context.Context, *Token, *Token) error
}

func RegisterUserServiceMicroHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		Create(ctx context.Context, in *User, out *Response) error
		Get(ctx context.Context, in *Getrequest, out *GetResponse) error
		GetUserTodos(ctx context.Context, in *Getrequest, out *GetAllTodoResponse) error
		GetAll(ctx context.Context, in *Request, out *GetAllResponse) error
		Updateuser(ctx context.Context, in *User, out *Response) error
		Deleteuser(ctx context.Context, in *User, out *DeleteResponse) error
		Auth(ctx context.Context, in *User, out *Token) error
		ValidateToken(ctx context.Context, in *Token, out *Token) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) Create(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.Create(ctx, in, out)
}

func (h *userServiceHandler) Get(ctx context.Context, in *Getrequest, out *GetResponse) error {
	return h.UserServiceHandler.Get(ctx, in, out)
}

func (h *userServiceHandler) GetUserTodos(ctx context.Context, in *Getrequest, out *GetAllTodoResponse) error {
	return h.UserServiceHandler.GetUserTodos(ctx, in, out)
}

func (h *userServiceHandler) GetAll(ctx context.Context, in *Request, out *GetAllResponse) error {
	return h.UserServiceHandler.GetAll(ctx, in, out)
}

func (h *userServiceHandler) Updateuser(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.Updateuser(ctx, in, out)
}

func (h *userServiceHandler) Deleteuser(ctx context.Context, in *User, out *DeleteResponse) error {
	return h.UserServiceHandler.Deleteuser(ctx, in, out)
}

func (h *userServiceHandler) Auth(ctx context.Context, in *User, out *Token) error {
	return h.UserServiceHandler.Auth(ctx, in, out)
}

func (h *userServiceHandler) ValidateToken(ctx context.Context, in *Token, out *Token) error {
	return h.UserServiceHandler.ValidateToken(ctx, in, out)
}

// Client API for TodoService service

type TodoService interface {
	TodoCreate(ctx context.Context, in *Todo, opts ...client.CallOption) (*TodoResponse, error)
	GetTodo(ctx context.Context, in *GetTodoRequest, opts ...client.CallOption) (*GetTodoResponse, error)
	GetAllTodos(ctx context.Context, in *GetAllTodoRequest, opts ...client.CallOption) (*GetAllTodoResponse, error)
	UpdateTodo(ctx context.Context, in *Todo, opts ...client.CallOption) (*TodoResponse, error)
	DeleteTodo(ctx context.Context, in *Todo, opts ...client.CallOption) (*DeleteTodoResponse, error)
}

type todoService struct {
	c    client.Client
	name string
}

func NewTodoService(name string, c client.Client) TodoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "usecase"
	}
	return &todoService{
		c:    c,
		name: name,
	}
}

func (c *todoService) TodoCreate(ctx context.Context, in *Todo, opts ...client.CallOption) (*TodoResponse, error) {
	req := c.c.NewRequest(c.name, "TodoService.TodoCreate", in)
	out := new(TodoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoService) GetTodo(ctx context.Context, in *GetTodoRequest, opts ...client.CallOption) (*GetTodoResponse, error) {
	req := c.c.NewRequest(c.name, "TodoService.GetTodo", in)
	out := new(GetTodoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoService) GetAllTodos(ctx context.Context, in *GetAllTodoRequest, opts ...client.CallOption) (*GetAllTodoResponse, error) {
	req := c.c.NewRequest(c.name, "TodoService.GetAllTodos", in)
	out := new(GetAllTodoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoService) UpdateTodo(ctx context.Context, in *Todo, opts ...client.CallOption) (*TodoResponse, error) {
	req := c.c.NewRequest(c.name, "TodoService.UpdateTodo", in)
	out := new(TodoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoService) DeleteTodo(ctx context.Context, in *Todo, opts ...client.CallOption) (*DeleteTodoResponse, error) {
	req := c.c.NewRequest(c.name, "TodoService.DeleteTodo", in)
	out := new(DeleteTodoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoService service

type TodoServiceHandler interface {
	TodoCreate(context.Context, *Todo, *TodoResponse) error
	GetTodo(context.Context, *GetTodoRequest, *GetTodoResponse) error
	GetAllTodos(context.Context, *GetAllTodoRequest, *GetAllTodoResponse) error
	UpdateTodo(context.Context, *Todo, *TodoResponse) error
	DeleteTodo(context.Context, *Todo, *DeleteTodoResponse) error
}

func RegisterTodoServiceMicroHandler(s server.Server, hdlr TodoServiceHandler, opts ...server.HandlerOption) error {
	type todoService interface {
		TodoCreate(ctx context.Context, in *Todo, out *TodoResponse) error
		GetTodo(ctx context.Context, in *GetTodoRequest, out *GetTodoResponse) error
		GetAllTodos(ctx context.Context, in *GetAllTodoRequest, out *GetAllTodoResponse) error
		UpdateTodo(ctx context.Context, in *Todo, out *TodoResponse) error
		DeleteTodo(ctx context.Context, in *Todo, out *DeleteTodoResponse) error
	}
	type TodoService struct {
		todoService
	}
	h := &todoServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TodoService{h}, opts...))
}

type todoServiceHandler struct {
	TodoServiceHandler
}

func (h *todoServiceHandler) TodoCreate(ctx context.Context, in *Todo, out *TodoResponse) error {
	return h.TodoServiceHandler.TodoCreate(ctx, in, out)
}

func (h *todoServiceHandler) GetTodo(ctx context.Context, in *GetTodoRequest, out *GetTodoResponse) error {
	return h.TodoServiceHandler.GetTodo(ctx, in, out)
}

func (h *todoServiceHandler) GetAllTodos(ctx context.Context, in *GetAllTodoRequest, out *GetAllTodoResponse) error {
	return h.TodoServiceHandler.GetAllTodos(ctx, in, out)
}

func (h *todoServiceHandler) UpdateTodo(ctx context.Context, in *Todo, out *TodoResponse) error {
	return h.TodoServiceHandler.UpdateTodo(ctx, in, out)
}

func (h *todoServiceHandler) DeleteTodo(ctx context.Context, in *Todo, out *DeleteTodoResponse) error {
	return h.TodoServiceHandler.DeleteTodo(ctx, in, out)
}
