// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package usecase

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Getrequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Getrequest) Reset()         { *m = Getrequest{} }
func (m *Getrequest) String() string { return proto.CompactTextString(m) }
func (*Getrequest) ProtoMessage()    {}
func (*Getrequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Getrequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Getrequest.Unmarshal(m, b)
}
func (m *Getrequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Getrequest.Marshal(b, m, deterministic)
}
func (m *Getrequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Getrequest.Merge(m, src)
}
func (m *Getrequest) XXX_Size() int {
	return xxx_messageInfo_Getrequest.Size(m)
}
func (m *Getrequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Getrequest.DiscardUnknown(m)
}

var xxx_messageInfo_Getrequest proto.InternalMessageInfo

func (m *Getrequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                *Token   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type GetResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                *Token   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type GetAllResonse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Token                *Token   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResonse) Reset()         { *m = GetAllResonse{} }
func (m *GetAllResonse) String() string { return proto.CompactTextString(m) }
func (*GetAllResonse) ProtoMessage()    {}
func (*GetAllResonse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *GetAllResonse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResonse.Unmarshal(m, b)
}
func (m *GetAllResonse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResonse.Marshal(b, m, deterministic)
}
func (m *GetAllResonse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResonse.Merge(m, src)
}
func (m *GetAllResonse) XXX_Size() int {
	return xxx_messageInfo_GetAllResonse.Size(m)
}
func (m *GetAllResonse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResonse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResonse proto.InternalMessageInfo

func (m *GetAllResonse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *GetAllResonse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type DeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                []*Error `protobuf:"bytes,3,rep,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetError() []*Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Getrequest)(nil), "usecase.Getrequest")
	proto.RegisterType((*Request)(nil), "usecase.Request")
	proto.RegisterType((*User)(nil), "usecase.User")
	proto.RegisterType((*Response)(nil), "usecase.Response")
	proto.RegisterType((*GetResponse)(nil), "usecase.GetResponse")
	proto.RegisterType((*GetAllResonse)(nil), "usecase.GetAllResonse")
	proto.RegisterType((*DeleteResponse)(nil), "usecase.DeleteResponse")
	proto.RegisterType((*Token)(nil), "usecase.Token")
	proto.RegisterType((*Error)(nil), "usecase.Error")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x6d, 0xd2, 0xa4, 0xed, 0x4e, 0xd4, 0x0a, 0x86, 0x15, 0xb2, 0x2a, 0x0e, 0xc1, 0x20, 0xb1,
	0x07, 0x54, 0x89, 0xc2, 0x95, 0xc3, 0x0a, 0x50, 0xb4, 0x07, 0x2e, 0x5e, 0x58, 0x09, 0x6e, 0x21,
	0x19, 0x89, 0x88, 0x6c, 0x1c, 0x6c, 0x67, 0x39, 0xf3, 0xcf, 0x91, 0xed, 0xe6, 0x83, 0x56, 0x48,
	0x1c, 0xf6, 0xe6, 0x37, 0x33, 0xef, 0xe5, 0xcd, 0x47, 0x00, 0x3a, 0x4d, 0x6a, 0xd7, 0x2a, 0x69,
	0x24, 0x2e, 0x3b, 0x4d, 0x45, 0xae, 0x89, 0x3f, 0x01, 0xc8, 0xc8, 0x28, 0xfa, 0xd9, 0x91, 0x36,
	0xb8, 0x81, 0xf0, 0xaa, 0x64, 0x41, 0x1a, 0x5c, 0xc4, 0x22, 0xbc, 0x2a, 0xf9, 0x19, 0x2c, 0x85,
	0x4f, 0x71, 0x05, 0xd1, 0x67, 0x4d, 0xca, 0x96, 0x54, 0x43, 0x49, 0x55, 0x22, 0x42, 0xd4, 0xe4,
	0xb7, 0xc4, 0xc2, 0x34, 0xb8, 0x38, 0x13, 0xee, 0x8d, 0xe7, 0x10, 0xd3, 0x6d, 0x5e, 0xd5, 0x6c,
	0xee, 0x82, 0x1e, 0xe0, 0x16, 0x56, 0x6d, 0xae, 0xf5, 0x2f, 0xa9, 0x4a, 0x16, 0xb9, 0xc4, 0x80,
	0x2d, 0xc3, 0xc8, 0x1f, 0xd4, 0xb0, 0xd8, 0x33, 0x1c, 0xe0, 0xd7, 0xb0, 0x12, 0xa4, 0x5b, 0xd9,
	0x68, 0xc2, 0xa7, 0x10, 0x59, 0xff, 0xee, 0xcb, 0xc9, 0x7e, 0xbd, 0x3b, 0x34, 0xb0, 0xb3, 0xa6,
	0x84, 0x4b, 0xe1, 0xf3, 0x5e, 0x24, 0x74, 0x35, 0x9b, 0xa1, 0xe6, 0x93, 0x8d, 0xf6, 0xa2, 0x37,
	0x90, 0x64, 0x64, 0xee, 0x5f, 0xf7, 0x2b, 0xac, 0x33, 0x32, 0x97, 0x75, 0x2d, 0x48, 0x3b, 0xe5,
	0x67, 0x10, 0x5b, 0xba, 0x66, 0x41, 0x3a, 0x3f, 0x95, 0xf6, 0xb9, 0xff, 0xd4, 0xfe, 0x08, 0x9b,
	0xf7, 0x54, 0x93, 0xa1, 0xc1, 0x36, 0x83, 0xa5, 0xee, 0x8a, 0x82, 0xb4, 0x76, 0xce, 0x57, 0xa2,
	0x87, 0x43, 0x43, 0xe1, 0x3f, 0x1b, 0xe2, 0x5f, 0x20, 0x76, 0xf2, 0xe3, 0xd8, 0x83, 0xc9, 0xd8,
	0x6d, 0xf4, 0x2e, 0xaf, 0xab, 0xd2, 0x49, 0xac, 0x84, 0x07, 0xd6, 0x29, 0x29, 0x25, 0x15, 0x9b,
	0xbb, 0x76, 0x46, 0xa7, 0x1f, 0x6c, 0x54, 0xf8, 0x24, 0x7f, 0x0b, 0xb1, 0xc3, 0xf6, 0x2e, 0x0a,
	0x59, 0xd2, 0xe1, 0x52, 0xdc, 0x1b, 0x53, 0x48, 0x4a, 0xd2, 0x85, 0xaa, 0x5a, 0x53, 0xc9, 0xe6,
	0x70, 0x32, 0xd3, 0xd0, 0xfe, 0x77, 0x08, 0x89, 0x35, 0x7a, 0x4d, 0xea, 0xae, 0x2a, 0x08, 0x5f,
	0xc2, 0xe2, 0x9d, 0xa2, 0xdc, 0x10, 0xfe, 0xdd, 0xc8, 0xf6, 0xe1, 0x00, 0xfb, 0x91, 0xf0, 0x19,
	0xee, 0x61, 0x9e, 0x91, 0xc1, 0x47, 0x43, 0x6e, 0x3c, 0xed, 0xed, 0xf9, 0x34, 0x38, 0xe1, 0xbc,
	0x81, 0x85, 0x5f, 0x1b, 0x3e, 0x98, 0x48, 0x7a, 0xce, 0xe3, 0x29, 0x67, 0xdc, 0x2c, 0x9f, 0xe1,
	0x0b, 0x88, 0x2e, 0x3b, 0xf3, 0xfd, 0xd8, 0xd5, 0xd1, 0xfa, 0xf8, 0x0c, 0x5f, 0xc1, 0xfa, 0xc6,
	0x8e, 0x2f, 0x37, 0xe4, 0x47, 0x7e, 0x54, 0x72, 0x4a, 0xf9, 0xb6, 0x70, 0xbf, 0xe8, 0xeb, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0x2a, 0xf9, 0x41, 0xb0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
	Get(ctx context.Context, in *Getrequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetAll(ctx context.Context, in *Request, opts ...grpc.CallOption) (*GetAllResonse, error)
	// rpc update (User) returns (Response){}
	// rpc Delete (User) returns (DeleteResponse){}
	Auth(ctx context.Context, in *User, opts ...grpc.CallOption) (*Token, error)
	ValidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/usecase.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *Getrequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/usecase.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAll(ctx context.Context, in *Request, opts ...grpc.CallOption) (*GetAllResonse, error) {
	out := new(GetAllResonse)
	err := c.cc.Invoke(ctx, "/usecase.UserService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Auth(ctx context.Context, in *User, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/usecase.UserService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ValidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/usecase.UserService/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *User) (*Response, error)
	Get(context.Context, *Getrequest) (*GetResponse, error)
	GetAll(context.Context, *Request) (*GetAllResonse, error)
	// rpc update (User) returns (Response){}
	// rpc Delete (User) returns (DeleteResponse){}
	Auth(context.Context, *User) (*Token, error)
	ValidateToken(context.Context, *Token) (*Token, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usecase.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Getrequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usecase.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*Getrequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usecase.UserService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAll(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usecase.UserService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Auth(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usecase.UserService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ValidateToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usecase.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _UserService_GetAll_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _UserService_Auth_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _UserService_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
